### PR TITLE
Windows x86_64 and Mac support

### PR DESCRIPTION
**Pull request by dioannidis**
Hi,

  I added support for windows x86_64 using the dll from the libusb/hidapi repo.

regards,

### CODE REVIEW

**Comment by dioannidis** [comment]
Also, now, it compiles and runs on Mac.

**Comment by prof7bit** [comment]
Hi, thank you for this PR. Would it be possible to factor out all these many repeated ifdefs in these function declarations (as below)

```pascal
function hid_read(device: PHidDevice; Data: Pointer; length: SizeInt): {$ifdef MSWINDOWS}LongInt{$else}cint{$endif}; HIDAPI_CALL; 
```

into one ifdef at the top, defining a new type that will be either an alias for LongInt or an alias for cint? That would probably be cleaner. Unfortunately I can't test it on Windows at the moment, but if it works this PR would be welcome.

**Comment by dioannidis** [comment]
Hi, 

  removed the ifdef's . Also removed the ctypes unit and replaced cint with integer. Tested in Windows 10 and Debian Buster 10.8 ( both x86_64 ).

regards,

**Comment by prof7bit** [comment]
I'm going to look at it when I have some time. It has been a while and I can't remember why I used the ctypes at all. It might take a few days because this week is going to be very busy with a lot of other stuff for me.

**Comment by dioannidis** [comment]
Do you think that you could find time and take a look on this ?

**Comment by dioannidis** [comment]
Closing cause no feedback.

**Pull request closed without merging**
